---
language: python
python:
    - "2.7"

env:
    global:
        - SSH_RSYNC="ssh -oIdentityFile=~/.ssh/id_nethbot -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null"
        - BUILD_DIR=admin-manual
        - TARGET_DIR=${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_TAG:-${TRAVIS_BRANCH}}}
        - SPHINX_OPTS="-b html -A current_version=${TARGET_DIR}"

before_install:
    - openssl aes-256-cbc -K $encrypted_d0b1a71bb301_key -iv $encrypted_d0b1a71bb301_iv -in id_nethbot_nethvoice.enc -out ~/.ssh/id_nethbot -d
    - chmod -c 600 ~/.ssh/id_nethbot

install:
    - pip install sphinx==1.7.4
    - pip install -r ${BUILD_DIR}/requirements.txt

script:
    - pushd ${BUILD_DIR}/
    - sphinx-build -D language=it ${SPHINX_OPTS} -d _build/doctrees/it . _build/webroot/it/${TARGET_DIR}
    - sphinx-build -D language=en ${SPHINX_OPTS} -d _build/doctrees/en . _build/webroot/en/${TARGET_DIR}
    - sphinx-build -D language=es ${SPHINX_OPTS} -d _build/doctrees/es . _build/webroot/es/${TARGET_DIR}
    - popd

deploy:
    provider: script
    skip_cleanup: true
    script: rsync -ai --no-super --delete-after -e "${SSH_RSYNC}" ${BUILD_DIR}/_build/webroot/{it,en,es}/* nethbot@docs1.nethserver.com:.
    on:
        all_branches: true
